apiVersion: v1
kind: Service
metadata:
  labels:
    app: otus-nginx
  name: otus-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    name: http
  - port: 9113
    protocol: TCP
    targetPort: 9113
    name: metrics
  selector:
    app: otus-nginx
  sessionAffinity: None
  type: ClusterIP