apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otus-nginx-sm
spec:
  selector:
    matchLabels:
      app: otus-nginx
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s