apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  rules:
  - host: {{ .Values.host}}
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: {{ .Values.service.port}}